# Workflow to automate fork alerts if forks are created outside of the original repository owner.
name: Fork Alert 
on: fork 
jobs:
  alert: 
    name: Create Alert Issue 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/some-other-template.md
        assignees: github.event.forkee.owner.logib
      if: github.event.forkee.owner.type != 'Organization'
