# Workflow to automate fork alerts if forks are created outside of the original repository owner.
name: Fork Email Alert 
on: fork 
jobs:  
   alert: 
    name: Send Alert Email 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dawidd6/action-send-mail@v2.1.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ALERT - Fork created outside of organization context
        # Literal body:
        body: Fork of ${{github.repository}} created outside of the organization context. 
        to: corydobson@github.com
        from: GitHub Fork Action Alert # <user@example.com>
        content_type: text/html  
      if: github.event.forkee.owner.type != 'Organization'
