# Workflow to automate fork alerts if forks are created outside of the original repository owner. 
name: Fork Alert 
on: [fork] 
jobs:
  validate:
       runs-on: ubuntu-latest
       steps:
        - name: Validate Fork 
          if: github.event_name == 'fork' 
          run: echo github.event.action
       
   alert:
    needs: validate
    name: Send Alert Email 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: dawidd6/action-send-mail@v2.1.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        # body: file://README.md
        to: corydobson@github.com
        from: GitHub Fork Action Alert # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
